AV 1056 implement gas sensor
ISSUIUC/MIDAS-Software pull request #10
Opened 2023-10-04 01:22 UTC by SuragNuthulapaty

added and implemented gas sensor stuff based on TARS

2023-10-07 22:12 UTC, aidancostello commented on MIDAS/src/systems.cpp
>          THREAD_SLEEP(16);
change the thread sleep to as closely match the maximum sampling rate as possible

2023-10-09 00:42 UTC, redindelible approved these changes

2023-10-09 00:42 UTC, redindelible commented on MIDAS/src/systems.cpp
> +        THREAD_SLEEP(5.5);
Does the fractional tick work?

2023-10-09 00:47 UTC, aidancostello requested changes
You also have to init the sensor in init_sensors() in systems.cpp

2023-10-09 00:47 UTC, aidancostello commented on MIDAS/src/hardware/Gas.cpp
> +    return {.humidity = humidity, .temperature = temperature, .pressure = pressure, .resistance = resistance};
this line doesn't build in platformio, something with the way that this is returned. you can maybe try { humidity, temperature, pressure, resistance};

2023-10-09 00:47 UTC, redindelible commented
Merge with master plz.

2023-10-10 22:07 UTC, aidancostello approved these changes
looks good, don't merge just yet

2023-10-11 00:57 UTC, aidancostello approved these changes

2023-10-11 02:55 UTC, merged