Av 1064 Camera Control
ISSUIUC/MIDAS-Software pull request #21
Opened 2023-10-31 23:19 UTC by ankithm28

2023-11-08 01:58 UTC, aidancostello requested changes
There are a few things that we have to change, I'll talk to you at the next meeting. I'm too lazy to write all the changes here.

2023-11-14 22:22 UTC, aidancostello requested changes
This all looks really good, it's just a matter of organization. I would create a header file to define certain globals, and rename the functions so that they're not setup and loop. Additionally, you should rebase/merge off of mvp_sensor_integration so you can get the pins.h file.

Lastly, you still need to have the thread actually call these functions. If you look at systems.cpp, you will need to make a new thread that calls the loop function with the argument of the fsm state, and add the setup function to the begin macro. You can look at the other sensor threads for guidance on how to do this after rebasing/merging

2023-11-14 22:22 UTC, aidancostello commented on MIDAS/src/hardware/Camera.cpp
> +static const byte MCP2517_SCK  = 0;
if you rebase/merge in mvp_sensor_integration, there is a pins.h file that defines pins for the general spi channel, so you can move these into that file. also, we want pins to be macros

2023-11-14 22:22 UTC, aidancostello commented on MIDAS/src/hardware/Camera.cpp
> +static const byte MCP2517_INT = 0;
we will not be using the interrupt pin. we can make the driver not look at the interrupt pin by making the pin 255. we also want to make this a macro as well

2023-11-14 22:22 UTC, aidancostello commented on MIDAS/src/hardware/Camera.cpp
> +  Serial.begin(9600);
serial will be begun in main.cpp, not here

2023-11-14 22:22 UTC, aidancostello commented on MIDAS/src/hardware/Camera.cpp
> +void setup () {
the setup function name is reserved for the setup function in main.cpp. you would want to call it something else, like can_setup or something else that makes sense, you can look at the other sensor implementations for ideas

2023-11-14 22:22 UTC, aidancostello commented on MIDAS/src/hardware/Camera.cpp
> +  while (!Serial) {
remove this if possible

2023-11-14 22:22 UTC, aidancostello commented on MIDAS/src/hardware/Camera.cpp
> +  SPI.begin (MCP2517_SCK, MCP2517_MISO, MCP2517_MOSI) ;
spi is begun globally in systems.cpp or main.cpp i forgot which, but you don't need to worry about beginning spi

2023-11-14 22:22 UTC, aidancostello commented on MIDAS/src/hardware/Camera.cpp
> +  if (debug) {
not sure what this debug is, but I'm not sure if we need it

2023-11-14 22:22 UTC, aidancostello commented on MIDAS/src/hardware/Camera.cpp
> +static unsigned gSendDate = 0 ;
i would recommend making a header file to store these variables instead of defining them here

2023-11-14 22:22 UTC, aidancostello commented on MIDAS/src/hardware/Camera.cpp
> +void loop (bool should_turn_cam_on) {
same with setup(), loop is a reserved function name, so call it something else. Also we would want to pass in the fsm state into this function as opposed to a straight bool. If we are in idle, we should turn on the camera, and turn off once we've landed. You can see the possible fsm states by looking at the fsm branch

2023-11-14 22:22 UTC, aidancostello commented on MIDAS/src/hardware/Camera.cpp
> +    message.id = 0x542 ;
have this be a global definition in a header file

2023-11-14 22:22 UTC, aidancostello commented on MIDAS/src/hardware/Camera.cpp
> +    Serial.print ("Received: ") ;
this is ok for debugging, but ideally this would be removed for the final version

2023-11-15 23:04 UTC, rbhog requested changes

2023-11-15 23:04 UTC, rbhog commented on MIDAS/src/hardware/Camera.cpp
> +  if (debug && can.receive (message)) {
nit: standardize how ur formatting function calls either do space or no space for everything (probably would prefer no space to keep consistent with everything else

2023-11-15 23:04 UTC, rbhog commented on MIDAS/src/hardware/Camera.cpp
> +    Serial.println (gReceivedCount) ;
nit: refer to previous comment on spaces

2023-11-15 23:04 UTC, rbhog commented on MIDAS/src/hardware/Camera.cpp
> +  const uint32_t errorCode = can.begin (settings, [] { can.isr () ; }) ;
nit: refer to comment on spaces

2023-11-15 23:04 UTC, rbhog commented on MIDAS/src/hardware/Camera.cpp
> +  ACAN2517Settings settings (ACAN2517Settings::OSC_4MHz10xPLL, 125 * 1000) ; // CAN bit rate 125 kb/s
probably better to have bitrate in a define or const, like to avoid magic numbers

2023-11-15 23:04 UTC, rbhog commented on MIDAS/src/hardware/Camera.cpp
> +  // Serial.println ("Configure ACAN2517") ;
delete dead code

2023-12-06 02:27 UTC, rbhog commented on MIDAS/src/hardware/Camera.cpp
> +#include "Camera.h"
nit: swap includes, do camera.h first then the libraries

2024-02-10 20:57 UTC, aidancostello requested changes

2024-02-10 20:57 UTC, aidancostello commented on MIDAS/src/systems.cpp
> +DECLARE_THREAD(camera, RocketSystems* arg) {
why do you tick the buzzer inside the camera thread but don't tick the camera control

2024-02-10 20:57 UTC, aidancostello commented on MIDAS/src/hardware/Camera.cpp
> +        THREAD_SLEEP(500);
why sleep inside the tick function, wouldn't it be better for readability if it's in the thread declaration where the rest of the thread sleeps are

2024-02-10 20:57 UTC, aidancostello commented on MIDAS/src/hardware/Camera.cpp
> +void can_loop(bool should_turn_cam_on) {
we could just pass in the fsm state to keep computation in the loop function. Just like if fsm state is not landed then camera on

2024-02-10 22:34 UTC, rbhog requested changes
literally 2 second change probably

2024-02-10 22:34 UTC, rbhog commented on MIDAS/src/hardware/Camera.cpp
> +}
nit: newline

2024-02-10 22:34 UTC, rbhog commented on MIDAS/src/hardware/pins.h
> +#define CAN_BIT_RATE 125000 // CAN bit rate 125 kb/s
nit: newline

2024-04-02 23:42 UTC, closed without merging