Av 1054 orientation
ISSUIUC/MIDAS-Software pull request #29
Opened 2023-11-29 03:30 UTC by jwu246

temp and pressure finished orientation.cpp and sensor_data.h

2023-11-29 16:05 UTC, redindelible requested changes
Make sure there's also an Orientation sensor thread

2023-11-29 16:05 UTC, redindelible commented on MIDAS/src/errors.h
> +    CANNOT_CONNECT_BNO,
match error naming style

2023-11-29 16:05 UTC, redindelible commented on MIDAS/src/hardware/Orientation.cpp
> +long reportIntervalUs = 5000;
make these two lines #define's

2023-11-29 16:05 UTC, redindelible commented on MIDAS/src/hardware/Orientation.cpp
> +    }
you're missing the `return sensor_reading;`

2023-11-29 21:31 UTC, aidancostello approved these changes

2023-12-02 23:18 UTC, redindelible approved these changes

2023-12-04 21:34 UTC, merged