GPS Sensor Fixes
ISSUIUC/MIDAS-Software pull request #41
Opened 2024-04-03 01:29 UTC by zyunlam

2024-04-03 02:01 UTC, NPIPHI requested changes
Gps coords should never end up in floats, not enough precision.

2024-04-03 02:01 UTC, NPIPHI commented on MIDAS/src/hardware/GPSSensor.cpp
> +    float lon = gpgga_message.xyz.lon * ((gpgga_message.xyz.ns == 'E') ? 1. : -1.);
These number should not be floats. Lat and lon need to be doubles to avoid rounding errors

2024-04-03 03:25 UTC, aidancostello approved these changes

2024-04-03 03:46 UTC, NPIPHI requested changes
still float issues

2024-04-03 03:46 UTC, NPIPHI commented on MIDAS/src/hardware/GPSSensor.cpp
> +    return GPS{static_cast<float>(lat), static_cast<float>(lon), alt, v, sat_count};
Still cannot be float at any point, floating point precision * earth circumference = hundred meter + errors

2024-04-04 02:02 UTC, NPIPHI approved these changes

2024-04-06 22:05 UTC, aidancostello approved these changes
lgtm

2024-04-06 22:06 UTC, merged