Av 1128 consolidate gss
ISSUIUC/MIDAS-Software pull request #44
Opened 2024-04-20 21:49 UTC by Aadityavoru

2024-04-23 03:54 UTC, mpkarpov-ui reviewed
Looks pretty good so far but can use some cleanup changes.. we will also need to change feather code in accordance with new telemetry packets.

2024-04-23 03:54 UTC, mpkarpov-ui commented on champaign_county_map.html
This file looks like it's auto-generated.. any way we can `.gitignore` it and instead include steps to generate it?

2024-04-23 03:54 UTC, mpkarpov-ui commented on ground/gss_combiner/README.md
This needs to be updated.. I will work on it once we settle on one final architecture for everything in this system.

2024-04-23 03:54 UTC, mpkarpov-ui commented on ground/gss_combiner/test/test.py
TODO: Documentation for the null-modem emulator setup/operation.

2024-04-23 03:54 UTC, mpkarpov-ui commented on ground/gss_combiner/util/mappy.py
Re: our conversation today-- we should move this out of the "gss combiner" space and more into "peripheral telemetry applications" space a la video system and live app.

2024-04-23 03:54 UTC, mpkarpov-ui commented on offline_osm_map.html
This also looks autogenerated, see my comment on the first map.

2024-04-23 23:33 UTC, redindelible requested changes
Don't commit files in __pycache__ (i.e. add **/*.pyc to .gitignore or something along those lines). 

Are the champaign _county_map.html or the bottomless map tiles required to be committed?

2024-10-06 19:58 UTC, mpkarpov-ui approved these changes
We should probably move some stuff from here to other locations (primarily map tiles). That being said as long as this works I'm ok having this being the software release for SG1.3

2024-10-06 19:58 UTC, mpkarpov-ui commented on ground/gss_combiner/main.py
> +def parse_params(arguments):
let's replace this with argparse

2024-10-06 19:58 UTC, mpkarpov-ui commented on ground/gss_combiner/util/mappy.py
> +    broker_address = "10.195.167.19"
hard coded?

2024-10-06 19:59 UTC, zyunlam approved these changes

2024-10-06 20:03 UTC, merged