Comments final
ISSUIUC/MIDAS-Software pull request #51
Opened 2024-04-27 23:14 UTC by SuragNuthulapaty

Added comments for all files in midas documenting code

2024-04-28 05:21 UTC, rbhog requested changes

2024-04-28 05:21 UTC, rbhog commented on MIDAS/src/data_logging.cpp
> + * Forward decleration of the id recieving function
what happened to the `@brief` here and capitalized ID

2024-04-28 05:21 UTC, rbhog commented on MIDAS/src/data_logging.cpp
> + * @brief wites a SensorData's entire queue reading to a sink
misspelled writes

2024-04-28 05:21 UTC, rbhog commented on MIDAS/src/data_logging.cpp
> + * @brief names a new fole for a log sink depending on the files currently on said LogSink
misspelled file

2024-04-28 05:21 UTC, rbhog commented on MIDAS/src/finite-state-machines/fsm.h
> + * @brief Holds current alttitude, acceleration, jerk, and speed values based off of averages and derivatives.
misspelled altitude

2024-04-28 05:21 UTC, rbhog commented on MIDAS/src/gnc/example_kf.h
>  class ExampleKalmanFilter : public KalmanFilter<9, 3>
imma have to update this template at some point, doesn't really work for extended kalman filters

2024-04-28 05:21 UTC, rbhog commented on MIDAS/src/hardware/Orientation.cpp
> + * @brief Takes a rotation quaternion and turns it into its Euler 3D counterpart
euler angles

2024-04-28 05:21 UTC, rbhog commented on MIDAS/src/hardware/Orientation.cpp
> + * @return Euler 3D vector representation of the quaternion
euler angle vector

2024-04-28 05:21 UTC, rbhog commented on MIDAS/src/hardware/Orientation.cpp
> + * @return Euler 3D vector representation of the quaternion
*euler angles*

2024-04-28 05:21 UTC, rbhog commented on MIDAS/src/hardware/telemetry_backend.cpp
> + * @brief Gets rssi of recent packets
capitalize rssi

2024-04-28 05:21 UTC, rbhog commented on MIDAS/src/hardware/telemetry_backend.cpp
> + * @param freq New frequence to set the LoRa module to
frequency

2024-04-28 05:21 UTC, rbhog commented on MIDAS/src/rocket_state.h
> + * @brief Wrapper for thread safe sensore data stroage
storage

2024-04-28 05:21 UTC, rbhog commented on MIDAS/src/rocket_state.h
> +     * @param data New data of the templeted type to add to queue
templated

2024-04-28 05:21 UTC, rbhog commented on MIDAS/src/sensor_data.h
> + * @brief euler represnetation of rotation
representation

2024-04-28 05:21 UTC, rbhog commented on MIDAS/src/sensor_data.h
> + * @brief data from the LowGLSM sensor
Low G LSM

2024-04-28 05:21 UTC, rbhog commented on MIDAS/src/telemetry_packet.h
> + * @brief format of the telemetry acket
packet

2024-05-13 22:52 UTC, aidancostello approved these changes

2024-05-14 00:36 UTC, rbhog approved these changes

2024-07-10 02:56 UTC, merged